name: 下载 BlueArchive ToSchool 网站文件并推送到当前分支
on:
  workflow_dispatch:

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Create destination directories
      run: |
        mkdir -p BlueArchive_2025_ToSchool/Build

    - name: Download files
      run: |
        wget -P BlueArchive_2025_ToSchool/ https://bluearchive.jp/toschool/index.html
        wget -P BlueArchive_2025_ToSchool/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/favicon.png
        wget -P BlueArchive_2025_ToSchool/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/1743132591562.style.css
        wget -P BlueArchive_2025_ToSchool/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/OGP.png
        wget -P BlueArchive_2025_ToSchool/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/horizontal.png
        wget -P BlueArchive_2025_ToSchool/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/study_role.png
        wget -P BlueArchive_2025_ToSchool/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/vconsole.min.js
        wget -P BlueArchive_2025_ToSchool/Build/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/Build/bb0d9ecdb05db3e84da20bd14a4f84dc.loader.js
        wget -P BlueArchive_2025_ToSchool/Build/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/Build/3421ab9513a4ca3fcbd9d259e9837d9a.framework.js
        wget -P BlueArchive_2025_ToSchool/Build/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/Build/03b653dd42a0101ed9ca509c384bf36c.wasm
        wget -P BlueArchive_2025_ToSchool/Build/ https://webusstatic.yo-star.com/bluearchive-jp/ba-jp-aprilfools-minigame/prod/minigame-2025/toschool/Build/3be0430b2d7e29efc39e2136b5fe7dd0.data

    - name: Set up Git LFS
      run: |
        git lfs install --system
        git lfs install --local --force # 显式安装本地钩子
        git lfs update --force

    - name: Track Large File with Git LFS
      run: |
        git lfs track "BlueArchive_2025_ToSchool/Build/3be0430b2d7e29efc39e2136b5fe7dd0.data"

    - name: List downloaded files
      run: ls -R BlueArchive_2025_ToSchool/

    - name: Add Files
      run: git add .

    - name: Commit Files
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "下载 BlueArchive ToSchool 网站文件并推送到当前分支"
        fi
    - name: Commit and push changes
      run: |
          git push origin ${{ github.ref_name }}

    - name: Check Git LFS Status (After Initial Push)
      run: git lfs status
